"""
PLOT360 Backend — Workflow Engine & Citizen Services ORM Models
Sections 10, 11, 41–44: Reusable workflow state machine, persistent service requests (SR-YYYY-XXXXXX),
and officer authorization transitions.
"""
from sqlalchemy import Column, String, Float, DateTime, Boolean, Integer, ForeignKey, Text, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.database import Base


class WorkflowTemplate(Base):
    """Configurable workflow definition template."""
    __tablename__ = "workflow_templates"

    id = Column(Integer, primary_key=True, index=True)
    code = Column(String(50), unique=True, nullable=False, index=True) # e.g. "MUTATION", "DEMARCATION", "NOC"
    name = Column(String(200), nullable=False)
    department = Column(String(200), nullable=False)
    steps_definition = Column(JSON, nullable=False)  # Ordered list of steps with required roles
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())


class WorkflowInstance(Base):
    """Active or completed workflow execution instance."""
    __tablename__ = "workflow_instances"

    id = Column(Integer, primary_key=True, index=True)
    template_id = Column(Integer, ForeignKey("workflow_templates.id"), nullable=True)
    entity_type = Column(String(100), nullable=False)  # "service_request", "application", "conflict"
    entity_id = Column(String(100), nullable=False, index=True) # e.g. "SR-2025-001027"
    parcel_id = Column(Integer, ForeignKey("parcels.id"), nullable=True)
    ulpin = Column(String(50), nullable=True, index=True)

    current_state = Column(String(100), default="SUBMITTED") # SUBMITTED -> DOCUMENTS_RECEIVED -> VERIFICATION -> DEPARTMENT_REVIEW -> FINAL_PROCESSING -> DECISION
    is_completed = Column(Boolean, default=False)
    final_decision = Column(String(50), nullable=True) # APPROVED / REJECTED / CANCELLED

    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    steps = relationship("WorkflowStep", back_populates="instance", cascade="all, delete-orphan")
    events = relationship("WorkflowEvent", back_populates="instance", cascade="all, delete-orphan")


class WorkflowStep(Base):
    """Individual milestone step in a workflow instance."""
    __tablename__ = "workflow_steps"

    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(Integer, ForeignKey("workflow_instances.id", ondelete="CASCADE"), nullable=False, index=True)
    step_name = Column(String(100), nullable=False)
    step_order = Column(Integer, nullable=False)
    required_role = Column(String(100), nullable=True)  # Role required to advance this step
    status = Column(String(50), default="PENDING")      # PENDING / IN_PROGRESS / COMPLETED / REJECTED / SKIPPED
    completed_by_id = Column(Integer, nullable=True)
    completed_by_name = Column(String(200), nullable=True)
    comments = Column(Text, nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)

    instance = relationship("WorkflowInstance", back_populates="steps")


class WorkflowEvent(Base):
    """Audit log of workflow state transitions."""
    __tablename__ = "workflow_events"

    id = Column(Integer, primary_key=True, index=True)
    instance_id = Column(Integer, ForeignKey("workflow_instances.id", ondelete="CASCADE"), nullable=False, index=True)
    from_state = Column(String(100), nullable=False)
    to_state = Column(String(100), nullable=False)
    actor_id = Column(Integer, nullable=True)
    actor_name = Column(String(200), nullable=True)
    actor_role = Column(String(100), nullable=True)
    comment = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    instance = relationship("WorkflowInstance", back_populates="events")


class ServiceRequest(Base):
    """
    Citizen-submitted service request.
    Section 42: Format SR-YYYY-XXXXXX, generated by backend and persistently stored.
    """
    __tablename__ = "service_requests"

    id = Column(Integer, primary_key=True, index=True)
    request_id = Column(String(50), unique=True, nullable=False, index=True) # e.g. "SR-2025-001027"
    parcel_id = Column(Integer, ForeignKey("parcels.id", ondelete="SET NULL"), nullable=True, index=True)
    ulpin = Column(String(50), nullable=True, index=True)
    citizen_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)

    service_type = Column(String(100), nullable=False)   # demarcation, mutation, noc, ror_copy, building_permission, encumbrance_certificate
    department = Column(String(200), nullable=False)
    applicant_name = Column(String(200), nullable=False)
    applicant_phone = Column(String(30), nullable=True)
    applicant_email = Column(String(100), nullable=True)

    status = Column(String(50), default="SUBMITTED")    # SUBMITTED / DOCUMENTS_RECEIVED / VERIFICATION / DEPARTMENT_REVIEW / FINAL_PROCESSING / DECISION
    current_step = Column(Integer, default=1)
    total_steps = Column(Integer, default=5)
    notes = Column(Text, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    parcel = relationship("Parcel", back_populates="service_requests")
    citizen = relationship("User", back_populates="service_requests")


class Application(Base):
    """General Land Administration Application entity."""
    __tablename__ = "applications"

    id = Column(Integer, primary_key=True, index=True)
    application_id = Column(String(100), unique=True, nullable=False, index=True)
    ulpin = Column(String(50), nullable=True, index=True)
    application_type = Column(String(100), nullable=False)
    applicant_name = Column(String(200), nullable=False)
    department = Column(String(200), nullable=False)
    status = Column(String(50), default="SUBMITTED")
    submission_date = Column(String(50), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
