"""
PLOT360 Backend — Demo Study Areas and Curated Parcel Data Registry
Phase 2, 3, 4, 5, 9, 10, 11: Authoritative multi-location study areas,
curated sample ULPINs, and spatially valid demo parcels across India.
"""
from typing import List, Dict, Any

# 10 Multi-Location Study Areas spanning diverse Indian land governance contexts
STUDY_AREAS_DATA: List[Dict[str, Any]] = [
    {
        "study_area_id": "chandigarh",
        "display_name": "Chandigarh Urban Center",
        "state_or_ut": "Chandigarh / Punjab",
        "district": "Chandigarh",
        "urban_rural_type": "Urban",
        "latitude": 30.7398,
        "longitude": 76.7794,
        "bounding_box": [76.7600, 30.7200, 76.8000, 30.7600],
        "sentinel_coverage": True,
        "sentinel_roi_id": "URB_01",
        "satellite_evidence_status": "AVAILABLE",
        "number_of_demo_plots": 4,
        "available_modules": [
            "ownership", "ror", "registration", "planning", "building",
            "liabilities", "tax", "utilities", "restrictions", "ai", "workflow"
        ],
        "demo_status": "ACTIVE_DEMO",
        "data_type": "DEMO/SAMPLE"
    },
    {
        "study_area_id": "mohali",
        "display_name": "SAS Nagar / Mohali Peri-Urban",
        "state_or_ut": "Punjab",
        "district": "SAS Nagar",
        "urban_rural_type": "Peri-Urban",
        "latitude": 30.7046,
        "longitude": 76.7179,
        "bounding_box": [76.7000, 30.6800, 76.7400, 30.7200],
        "sentinel_coverage": True,
        "sentinel_roi_id": "AGR_01",
        "satellite_evidence_status": "AVAILABLE",
        "number_of_demo_plots": 3,
        "available_modules": [
            "ownership", "ror", "registration", "planning", "building",
            "tax", "utilities", "ai", "workflow"
        ],
        "demo_status": "ACTIVE_DEMO",
        "data_type": "DEMO/SAMPLE"
    },
    {
        "study_area_id": "panchkula",
        "display_name": "Panchkula Shivalik Foothills",
        "state_or_ut": "Haryana",
        "district": "Panchkula",
        "urban_rural_type": "Peri-Urban / Hill Fringe",
        "latitude": 30.6942,
        "longitude": 76.8606,
        "bounding_box": [76.8400, 30.6700, 76.8800, 30.7100],
        "sentinel_coverage": True,
        "sentinel_roi_id": "MTN_01",
        "satellite_evidence_status": "AVAILABLE",
        "number_of_demo_plots": 3,
        "available_modules": [
            "ownership", "ror", "registration", "planning", "building",
            "tax", "utilities", "restrictions", "ai"
        ],
        "demo_status": "ACTIVE_DEMO",
        "data_type": "DEMO/SAMPLE"
    },
    {
        "study_area_id": "delhi_ncr",
        "display_name": "Delhi NCR Metropolitan Study Area",
        "state_or_ut": "Delhi NCT",
        "district": "South Delhi",
        "urban_rural_type": "Urban Metropolitan",
        "latitude": 28.5355,
        "longitude": 77.2410,
        "bounding_box": [77.2200, 28.5100, 77.2600, 28.5600],
        "sentinel_coverage": True,
        "sentinel_roi_id": "URB_02",
        "satellite_evidence_status": "AVAILABLE",
        "number_of_demo_plots": 3,
        "available_modules": [
            "ownership", "ror", "registration", "planning", "building",
            "liabilities", "tax", "utilities", "ai"
        ],
        "demo_status": "ACTIVE_DEMO",
        "data_type": "DEMO/SAMPLE"
    },
    {
        "study_area_id": "jaipur",
        "display_name": "Jaipur Heritage & Arid Corridor",
        "state_or_ut": "Rajasthan",
        "district": "Jaipur",
        "urban_rural_type": "Urban / Arid Fringe",
        "latitude": 26.9124,
        "longitude": 75.7873,
        "bounding_box": [75.7600, 26.8900, 75.8100, 26.9300],
        "sentinel_coverage": True,
        "sentinel_roi_id": "URB_04",
        "satellite_evidence_status": "AVAILABLE",
        "number_of_demo_plots": 3,
        "available_modules": [
            "ownership", "ror", "registration", "planning", "building",
            "tax", "utilities", "restrictions", "ai"
        ],
        "demo_status": "ACTIVE_DEMO",
        "data_type": "DEMO/SAMPLE"
    },
    {
        "study_area_id": "bengaluru",
        "display_name": "Bengaluru High-Tech Corridor",
        "state_or_ut": "Karnataka",
        "district": "Bengaluru Urban",
        "urban_rural_type": "High-Tech Urban",
        "latitude": 12.9716,
        "longitude": 77.5946,
        "bounding_box": [77.5700, 12.9500, 77.6200, 12.9900],
        "sentinel_coverage": True,
        "sentinel_roi_id": "URB_03",
        "satellite_evidence_status": "AVAILABLE",
        "number_of_demo_plots": 3,
        "available_modules": [
            "ownership", "ror", "registration", "planning", "building",
            "liabilities", "tax", "utilities", "ai"
        ],
        "demo_status": "ACTIVE_DEMO",
        "data_type": "DEMO/SAMPLE"
    },
    {
        "study_area_id": "kochi",
        "display_name": "Kochi Coastal & Backwaters Study Area",
        "state_or_ut": "Kerala",
        "district": "Ernakulam",
        "urban_rural_type": "Coastal Zone",
        "latitude": 9.9312,
        "longitude": 76.2673,
        "bounding_box": [76.2400, 9.9100, 76.2900, 9.9500],
        "sentinel_coverage": True,
        "sentinel_roi_id": "CST_01",
        "satellite_evidence_status": "AVAILABLE",
        "number_of_demo_plots": 3,
        "available_modules": [
            "ownership", "ror", "registration", "planning", "restrictions",
            "tax", "utilities", "ai"
        ],
        "demo_status": "ACTIVE_DEMO",
        "data_type": "DEMO/SAMPLE"
    },
    {
        "study_area_id": "varanasi_rural",
        "display_name": "Rural Varanasi / Indo-Gangetic Alluvial",
        "state_or_ut": "Uttar Pradesh",
        "district": "Varanasi",
        "urban_rural_type": "Rural Village Settlement",
        "latitude": 25.3176,
        "longitude": 82.9739,
        "bounding_box": [82.9500, 25.2900, 83.0000, 25.3400],
        "sentinel_coverage": True,
        "sentinel_roi_id": "RUR_01",
        "satellite_evidence_status": "AVAILABLE",
        "number_of_demo_plots": 3,
        "available_modules": [
            "ownership", "ror", "registration", "planning", "tax",
            "restrictions", "ai", "workflow"
        ],
        "demo_status": "ACTIVE_DEMO",
        "data_type": "DEMO/SAMPLE"
    },
    {
        "study_area_id": "pune_industrial",
        "display_name": "Pune Industrial Corridor",
        "state_or_ut": "Maharashtra",
        "district": "Pune",
        "urban_rural_type": "Industrial Corridor",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "bounding_box": [73.8300, 18.5000, 73.8800, 18.5400],
        "sentinel_coverage": True,
        "sentinel_roi_id": "IND_01",
        "satellite_evidence_status": "AVAILABLE",
        "number_of_demo_plots": 3,
        "available_modules": [
            "ownership", "ror", "registration", "planning", "building",
            "liabilities", "tax", "utilities", "ai"
        ],
        "demo_status": "ACTIVE_DEMO",
        "data_type": "DEMO/SAMPLE"
    },
    {
        "study_area_id": "shimla_hills",
        "display_name": "Shimla Hill Terrain (Non-Sentinel Study Area)",
        "state_or_ut": "Himachal Pradesh",
        "district": "Shimla",
        "urban_rural_type": "Mountain / Slope Settlement",
        "latitude": 31.1048,
        "longitude": 77.1734,
        "bounding_box": [77.1500, 31.0800, 77.2000, 31.1300],
        "sentinel_coverage": False,
        "sentinel_roi_id": None,
        "satellite_evidence_status": "NOT_AVAILABLE_FOR_THIS_DEMO_LOCATION",
        "number_of_demo_plots": 3,
        "available_modules": [
            "ownership", "ror", "registration", "planning", "restrictions",
            "tax", "utilities"
        ],
        "demo_status": "ACTIVE_DEMO",
        "data_type": "DEMO/SAMPLE"
    }
]

# 31 Curated Demo Parcels Across All 10 Study Areas
DEMO_PARCELS_DATA: List[Dict[str, Any]] = [
    # ── Chandigarh Study Area (4 plots) ───────────────────────────────────────
    {
        "parcel_id": "P-1027",
        "ulpin": "IN-PB-CHD-0001027",
        "survey_no": "1027/A",
        "khata_no": "KH-842",
        "location": "Sector 17, Chandigarh",
        "location_id": "chandigarh",
        "state": "Punjab",
        "district": "Chandigarh",
        "tehsil": "Chandigarh Central",
        "rural_urban": "Urban",
        "original_area": 0.31,
        "original_unit": "Acre",
        "standardized_area": 1248.50,
        "standardized_unit": "m²",
        "area_display": "1,248.50 m²",
        "original_area_display": "0.31 Acre",
        "land_use": "Residential",
        "zoning": "Residential (R-2)",
        "jurisdiction": "Chandigarh",
        "status": "Verified",
        "centroid_lat": 30.7392,
        "centroid_lng": 76.7818,
        "demo_scenario": "Profile A: Complete Integrated Urban Parcel",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "liabilities", "tax", "utilities", "restrictions", "ai"],
        "owner": {"name": "Ravinder Singh", "relation": "s/o Harbhajan Singh", "share": "100%"},
        "bp": {"id": "PJB/BP/2023/114", "status": "Approved", "floors": "G + 2", "date": "14 Nov 2023"},
        "enc": {"status": "Active", "inst": "HDFC Bank Ltd.", "amt": "₹ 45,00,000", "noc": True, "ref": "MORT-2023-098"},
        "tax": {"id": "PT-CHD-2024-8902", "status": "Paid", "paid": "₹ 18,400", "date": "28 Jun 2024"},
        "ut": {"elec": "Connected (Meter #99210)", "water": "Connected (Connection #4412)", "sewer": "Connected", "gas": "Available Nearby"},
        "coords": [
            {"lat": 30.7398, "lng": 76.7794},
            {"lat": 30.7412, "lng": 76.7820},
            {"lat": 30.7385, "lng": 76.7842},
            {"lat": 30.7371, "lng": 76.7816}
        ]
    },
    {
        "parcel_id": "P-1025",
        "ulpin": "IN-PB-CHD-0001025",
        "survey_no": "1025",
        "khata_no": "KH-840",
        "location": "Sector 17, Chandigarh",
        "location_id": "chandigarh",
        "state": "Punjab",
        "district": "Chandigarh",
        "tehsil": "Chandigarh Central",
        "rural_urban": "Urban",
        "original_area": 0.28,
        "original_unit": "Acre",
        "standardized_area": 1133.12,
        "standardized_unit": "m²",
        "area_display": "1,133.12 m²",
        "original_area_display": "0.28 Acre",
        "land_use": "Commercial",
        "zoning": "Commercial (C-1)",
        "jurisdiction": "Chandigarh",
        "status": "Verified",
        "centroid_lat": 30.7412,
        "centroid_lng": 76.7842,
        "demo_scenario": "Profile C: Planning & Zoning-Heavy Commercial Parcel",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "tax", "utilities"],
        "owner": {"name": "Amrik Builders & Promoters", "relation": "Ltd.", "share": "100%"},
        "bp": {"id": "PJB/BP/2022/881", "status": "Approved", "floors": "G + 4", "date": "10 Jan 2022"},
        "enc": {"status": "Clear"},
        "tax": {"id": "PT-CHD-2024-8900", "status": "Paid", "paid": "₹ 34,200", "date": "15 Jul 2024"},
        "ut": {"elec": "Connected", "water": "Connected", "sewer": "Connected", "gas": "Connected"},
        "coords": [
            {"lat": 30.7415, "lng": 76.7825},
            {"lat": 30.7428, "lng": 76.7845},
            {"lat": 30.7410, "lng": 76.7860},
            {"lat": 30.7397, "lng": 76.7840}
        ]
    },
    {
        "parcel_id": "P-1026",
        "ulpin": "IN-PB-CHD-0001026",
        "survey_no": "1026",
        "khata_no": "KH-841",
        "location": "Sector 17, Chandigarh",
        "location_id": "chandigarh",
        "state": "Punjab",
        "district": "Chandigarh",
        "tehsil": "Chandigarh Central",
        "rural_urban": "Urban",
        "original_area": 0.45,
        "original_unit": "Acre",
        "standardized_area": 1821.08,
        "standardized_unit": "m²",
        "area_display": "1,821.08 m²",
        "original_area_display": "0.45 Acre",
        "land_use": "Residential",
        "zoning": "Residential (R-2)",
        "jurisdiction": "Chandigarh",
        "status": "Verified",
        "centroid_lat": 30.7380,
        "centroid_lng": 76.7788,
        "demo_scenario": "Profile D: Parcel with Encumbrance & Mortgage Lien",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "liabilities", "tax", "utilities"],
        "owner": {"name": "Gurpreet Kaur", "relation": "w/o Jaswant Singh", "share": "100%"},
        "bp": {"id": "PJB/BP/2024/012", "status": "Under Review", "floors": "G + 2", "date": "05 Mar 2024"},
        "enc": {"status": "Active", "inst": "Punjab National Bank", "amt": "₹ 28,00,000", "noc": True, "ref": "PNB-2023-771"},
        "tax": {"id": "PT-CHD-2024-8901", "status": "Paid", "paid": "₹ 21,500", "date": "10 Aug 2024"},
        "ut": {"elec": "Connected", "water": "Connected", "sewer": "Connected", "gas": "Available Nearby"},
        "coords": [
            {"lat": 30.7385, "lng": 76.7765},
            {"lat": 30.7398, "lng": 76.7790},
            {"lat": 30.7375, "lng": 76.7810},
            {"lat": 30.7362, "lng": 76.7785}
        ]
    },
    {
        "parcel_id": "P-1028",
        "ulpin": "IN-PB-CHD-0001028",
        "survey_no": "1028",
        "khata_no": "KH-843",
        "location": "Sector 17, Chandigarh",
        "location_id": "chandigarh",
        "state": "Punjab",
        "district": "Chandigarh",
        "tehsil": "Chandigarh Central",
        "rural_urban": "Urban",
        "original_area": 0.24,
        "original_unit": "Acre",
        "standardized_area": 980.40,
        "standardized_unit": "m²",
        "area_display": "980.40 m²",
        "original_area_display": "0.24 Acre",
        "land_use": "Mixed Use",
        "zoning": "Commercial / Mixed (M-1)",
        "jurisdiction": "Chandigarh",
        "status": "Flagged",
        "centroid_lat": 30.7365,
        "centroid_lng": 76.7825,
        "demo_scenario": "Profile G: Parcel with AI Temporal Evidence & Change Alert",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "tax", "ai"],
        "owner": {"name": "Balwinder Singh & Sons", "relation": "HUF", "share": "100%"},
        "bp": {"id": "PJB/BP/2023/409", "status": "Approved", "floors": "G + 3", "date": "18 Sep 2023"},
        "enc": {"status": "Clear"},
        "tax": {"id": "PT-CHD-2024-8903", "status": "Paid", "paid": "₹ 16,800", "date": "12 May 2024"},
        "ut": {"elec": "Connected", "water": "Connected", "sewer": "Connected", "gas": "Available Nearby"},
        "coords": [
            {"lat": 30.7370, "lng": 76.7810},
            {"lat": 30.7380, "lng": 76.7830},
            {"lat": 30.7360, "lng": 76.7840},
            {"lat": 30.7350, "lng": 76.7820}
        ]
    },

    # ── Mohali Peri-Urban (3 plots) ───────────────────────────────────────────
    {
        "parcel_id": "P-2041",
        "ulpin": "IN-PB-SAS-0002041",
        "survey_no": "2041",
        "khata_no": "KH-310",
        "location": "Sector 70, SAS Nagar (Mohali)",
        "location_id": "mohali",
        "state": "Punjab",
        "district": "SAS Nagar",
        "tehsil": "Mohali",
        "rural_urban": "Peri-Urban",
        "original_area": 0.60,
        "original_unit": "Acre",
        "standardized_area": 2428.11,
        "standardized_unit": "m²",
        "area_display": "2,428.11 m²",
        "original_area_display": "0.60 Acre",
        "land_use": "Residential",
        "zoning": "Residential (R-1)",
        "jurisdiction": "Punjab",
        "status": "Verified",
        "centroid_lat": 30.7046,
        "centroid_lng": 76.7179,
        "demo_scenario": "Profile B: Rural-to-Urban Agricultural Transition Parcel",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "tax", "utilities", "ai"],
        "owner": {"name": "Sukhdev Singh Dhillon", "relation": "s/o Jagir Singh", "share": "100%"},
        "bp": {"id": "SAS/BP/2023/089", "status": "Approved", "floors": "G + 2", "date": "11 Oct 2023"},
        "enc": {"status": "Clear"},
        "tax": {"id": "PT-SAS-2024-5102", "status": "Paid", "paid": "₹ 14,200", "date": "19 Jun 2024"},
        "ut": {"elec": "Connected", "water": "Connected", "sewer": "Connected", "gas": "Not Connected"},
        "coords": [
            {"lat": 30.7056, "lng": 76.7165},
            {"lat": 30.7068, "lng": 76.7188},
            {"lat": 30.7038, "lng": 76.7202},
            {"lat": 30.7025, "lng": 76.7178}
        ]
    },
    {
        "parcel_id": "P-2042",
        "ulpin": "IN-PB-SAS-0002042",
        "survey_no": "2042",
        "khata_no": "KH-311",
        "location": "Sector 71, SAS Nagar (Mohali)",
        "location_id": "mohali",
        "state": "Punjab",
        "district": "SAS Nagar",
        "tehsil": "Mohali",
        "rural_urban": "Peri-Urban",
        "original_area": 0.38,
        "original_unit": "Acre",
        "standardized_area": 1550.00,
        "standardized_unit": "m²",
        "area_display": "1,550.00 m²",
        "original_area_display": "0.38 Acre",
        "land_use": "Commercial",
        "zoning": "Commercial (C-2)",
        "jurisdiction": "Punjab",
        "status": "Verified",
        "centroid_lat": 30.7075,
        "centroid_lng": 76.7210,
        "demo_scenario": "Profile E: Parcel with Infrastructure & Civic Utility Records",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "tax", "utilities"],
        "owner": {"name": "Gurcharan Enterprises", "relation": "Partnership", "share": "100%"},
        "bp": {"id": "SAS/BP/2023/155", "status": "Approved", "floors": "G + 3", "date": "04 Dec 2023"},
        "enc": {"status": "Clear"},
        "tax": {"id": "PT-SAS-2024-5103", "status": "Paid", "paid": "₹ 22,100", "date": "02 Jul 2024"},
        "ut": {"elec": "Connected (3-Phase)", "water": "Connected", "sewer": "Connected", "gas": "Available Nearby"},
        "coords": [
            {"lat": 30.7085, "lng": 76.7198},
            {"lat": 30.7095, "lng": 76.7220},
            {"lat": 30.7070, "lng": 76.7230},
            {"lat": 30.7060, "lng": 76.7208}
        ]
    },
    {
        "parcel_id": "P-2043",
        "ulpin": "IN-PB-SAS-0002043",
        "survey_no": "2043",
        "khata_no": "KH-312",
        "location": "Sector 72, SAS Nagar (Mohali)",
        "location_id": "mohali",
        "state": "Punjab",
        "district": "SAS Nagar",
        "tehsil": "Mohali",
        "rural_urban": "Peri-Urban",
        "original_area": 0.79,
        "original_unit": "Acre",
        "standardized_area": 3200.00,
        "standardized_unit": "m²",
        "area_display": "3,200.00 m²",
        "original_area_display": "0.79 Acre",
        "land_use": "Institutional",
        "zoning": "Institutional (I-1)",
        "jurisdiction": "Punjab",
        "status": "Flagged",
        "centroid_lat": 30.7015,
        "centroid_lng": 76.7150,
        "demo_scenario": "Profile F: Parcel with Area Conflict Requiring Officer Review",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "tax", "conflict"],
        "owner": {"name": "Mohali Education Trust", "relation": "Registered Society", "share": "100%"},
        "enc": {"status": "Clear"},
        "tax": {"id": "PT-SAS-2024-5104", "status": "Paid", "paid": "₹ 38,000", "date": "14 May 2024"},
        "ut": {"elec": "Connected", "water": "Connected", "sewer": "Connected", "gas": "Not Connected"},
        "coords": [
            {"lat": 30.7025, "lng": 76.7135},
            {"lat": 30.7035, "lng": 76.7162},
            {"lat": 30.7005, "lng": 76.7170},
            {"lat": 30.6995, "lng": 76.7142}
        ]
    },

    # ── Panchkula Foothills (3 plots) ─────────────────────────────────────────
    {
        "parcel_id": "P-3082",
        "ulpin": "IN-HR-PKL-0003082",
        "survey_no": "3082",
        "khata_no": "KH-901",
        "location": "Sector 5, Panchkula",
        "location_id": "panchkula",
        "state": "Haryana",
        "district": "Panchkula",
        "tehsil": "Panchkula",
        "rural_urban": "Peri-Urban",
        "original_area": 0.26,
        "original_unit": "Acre",
        "standardized_area": 1050.00,
        "standardized_unit": "m²",
        "area_display": "1,050.00 m²",
        "original_area_display": "0.26 Acre",
        "land_use": "Residential",
        "zoning": "Residential (R-1)",
        "jurisdiction": "Haryana",
        "status": "Verified",
        "centroid_lat": 30.6942,
        "centroid_lng": 76.8606,
        "demo_scenario": "Profile C: Foothill Slope & Eco-Sensitive Zone Restrictions",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "restrictions", "tax"],
        "owner": {"name": "Col. Jagdish Chander (Retd.)", "relation": "s/o K. L. Chander", "share": "100%"},
        "bp": {"id": "HR/BP/2023/702", "status": "Approved", "floors": "G + 2", "date": "19 Aug 2023"},
        "enc": {"status": "Clear"},
        "tax": {"id": "PT-PKL-2024-1209", "status": "Paid", "paid": "₹ 15,300", "date": "22 Jul 2024"},
        "ut": {"elec": "Connected", "water": "Connected", "sewer": "Connected", "gas": "Available Nearby"},
        "coords": [
            {"lat": 30.6952, "lng": 76.8590},
            {"lat": 30.6965, "lng": 76.8615},
            {"lat": 30.6938, "lng": 76.8625},
            {"lat": 30.6925, "lng": 76.8608}
        ]
    },
    {
        "parcel_id": "P-3083",
        "ulpin": "IN-HR-PKL-0003083",
        "survey_no": "3083",
        "khata_no": "KH-902",
        "location": "Sector 4, Panchkula",
        "location_id": "panchkula",
        "state": "Haryana",
        "district": "Panchkula",
        "tehsil": "Panchkula",
        "rural_urban": "Urban",
        "original_area": 0.35,
        "original_unit": "Acre",
        "standardized_area": 1420.00,
        "standardized_unit": "m²",
        "area_display": "1,420.00 m²",
        "original_area_display": "0.35 Acre",
        "land_use": "Residential",
        "zoning": "Residential (R-2)",
        "jurisdiction": "Haryana",
        "status": "Verified",
        "centroid_lat": 30.6965,
        "centroid_lng": 76.8635,
        "demo_scenario": "Profile A: Verified Suburban Plotted Development",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "tax", "utilities"],
        "owner": {"name": "Shalini Verma", "relation": "w/o Vikram Verma", "share": "100%"},
        "bp": {"id": "HR/BP/2024/044", "status": "Approved", "floors": "G + 2", "date": "16 Feb 2024"},
        "enc": {"status": "Clear"},
        "tax": {"id": "PT-PKL-2024-1210", "status": "Paid", "paid": "₹ 19,400", "date": "08 Aug 2024"},
        "ut": {"elec": "Connected", "water": "Connected", "sewer": "Connected", "gas": "Connected"},
        "coords": [
            {"lat": 30.6975, "lng": 76.8620},
            {"lat": 30.6985, "lng": 76.8645},
            {"lat": 30.6955, "lng": 76.8655},
            {"lat": 30.6945, "lng": 76.8630}
        ]
    },
    {
        "parcel_id": "P-3084",
        "ulpin": "IN-HR-PKL-0003084",
        "survey_no": "3084",
        "khata_no": "KH-903",
        "location": "Sector 6, Panchkula",
        "location_id": "panchkula",
        "state": "Haryana",
        "district": "Panchkula",
        "tehsil": "Panchkula",
        "rural_urban": "Urban",
        "original_area": 0.52,
        "original_unit": "Acre",
        "standardized_area": 2100.00,
        "standardized_unit": "m²",
        "area_display": "2,100.00 m²",
        "original_area_display": "0.52 Acre",
        "land_use": "Civic Amenities",
        "zoning": "Public / Semi-Public (P-1)",
        "jurisdiction": "Haryana",
        "status": "Verified",
        "centroid_lat": 30.6918,
        "centroid_lng": 76.8580,
        "demo_scenario": "Profile E: HSVP Planned Civic Facility with Smart Utilities",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "tax", "utilities"],
        "owner": {"name": "Haryana Shehri Vikas Pradhikaran", "relation": "Govt Body", "share": "100%"},
        "enc": {"status": "Clear"},
        "tax": {"id": "PT-PKL-2024-1211", "status": "Exempt", "paid": "₹ 0", "date": "01 Apr 2024"},
        "ut": {"elec": "Connected", "water": "Connected", "sewer": "Connected", "gas": "Available Nearby"},
        "coords": [
            {"lat": 30.6928, "lng": 76.8565},
            {"lat": 30.6938, "lng": 76.8592},
            {"lat": 30.6908, "lng": 76.8600},
            {"lat": 30.6898, "lng": 76.8572}
        ]
    },

    # ── Delhi NCR Metropolitan (3 plots) ──────────────────────────────────────
    {
        "parcel_id": "P-4101",
        "ulpin": "IN-DL-SDH-0004101",
        "survey_no": "4101",
        "khata_no": "DL-KH-102",
        "location": "Saket District Centre, South Delhi",
        "location_id": "delhi_ncr",
        "state": "Delhi NCT",
        "district": "South Delhi",
        "tehsil": "Hauz Khas",
        "rural_urban": "Urban",
        "original_area": 0.46,
        "original_unit": "Acre",
        "standardized_area": 1850.00,
        "standardized_unit": "m²",
        "area_display": "1,850.00 m²",
        "original_area_display": "0.46 Acre",
        "land_use": "Commercial",
        "zoning": "District Commercial Center (DDA MPD-2041)",
        "jurisdiction": "Delhi NCT",
        "status": "Verified",
        "centroid_lat": 28.5355,
        "centroid_lng": 77.2410,
        "demo_scenario": "Profile A: DDA Master Plan 2041 Transit Corridor Plot",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "tax", "utilities", "ai"],
        "owner": {"name": "Capital Prime Assets LLP", "relation": "Registered Entity", "share": "100%"},
        "bp": {"id": "DDA/BP/2023/910", "status": "Approved", "floors": "G + 5", "date": "29 Nov 2023"},
        "enc": {"status": "Clear"},
        "tax": {"id": "MCD-TAX-2024-9920", "status": "Paid", "paid": "₹ 95,000", "date": "14 May 2024"},
        "ut": {"elec": "Connected (BSES Rajdhani)", "water": "Connected (DJB)", "sewer": "Connected", "gas": "IGL Piped Gas"},
        "coords": [
            {"lat": 28.5365, "lng": 77.2395},
            {"lat": 28.5375, "lng": 77.2422},
            {"lat": 28.5345, "lng": 77.2430},
            {"lat": 28.5335, "lng": 77.2402}
        ]
    },
    {
        "parcel_id": "P-4102",
        "ulpin": "IN-DL-SDH-0004102",
        "survey_no": "4102",
        "khata_no": "DL-KH-103",
        "location": "Mehrauli Heritage Fringe, South Delhi",
        "location_id": "delhi_ncr",
        "state": "Delhi NCT",
        "district": "South Delhi",
        "tehsil": "Mehrauli",
        "rural_urban": "Urban",
        "original_area": 0.30,
        "original_unit": "Acre",
        "standardized_area": 1200.00,
        "standardized_unit": "m²",
        "area_display": "1,200.00 m²",
        "original_area_display": "0.30 Acre",
        "land_use": "Residential",
        "zoning": "Special Heritage Controlled Zone (R-3)",
        "jurisdiction": "Delhi NCT",
        "status": "Verified",
        "centroid_lat": 28.5380,
        "centroid_lng": 77.2440,
        "demo_scenario": "Profile D: Heritage Buffer Sub-Leasehold with Bank Lien",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "liabilities", "tax"],
        "owner": {"name": "Kailash Chand Mittal", "relation": "s/o O. P. Mittal", "share": "100%"},
        "bp": {"id": "MCD/BP/2022/412", "status": "Approved", "floors": "G + 2", "date": "10 Jun 2022"},
        "enc": {"status": "Active", "inst": "State Bank of India", "amt": "₹ 75,00,000", "noc": True, "ref": "SBI-DL-2023-441"},
        "tax": {"id": "MCD-TAX-2024-9921", "status": "Paid", "paid": "₹ 32,400", "date": "30 Jun 2024"},
        "ut": {"elec": "Connected", "water": "Connected", "sewer": "Connected", "gas": "IGL Piped Gas"},
        "coords": [
            {"lat": 28.5390, "lng": 77.2425},
            {"lat": 28.5400, "lng": 77.2452},
            {"lat": 28.5370, "lng": 77.2460},
            {"lat": 28.5360, "lng": 77.2432}
        ]
    },
    {
        "parcel_id": "P-4103",
        "ulpin": "IN-DL-SDH-0004103",
        "survey_no": "4103",
        "khata_no": "DL-KH-104",
        "location": "Pushp Vihar, South Delhi",
        "location_id": "delhi_ncr",
        "state": "Delhi NCT",
        "district": "South Delhi",
        "tehsil": "Saket",
        "rural_urban": "Urban",
        "original_area": 0.64,
        "original_unit": "Acre",
        "standardized_area": 2600.00,
        "standardized_unit": "m²",
        "area_display": "2,600.00 m²",
        "original_area_display": "0.64 Acre",
        "land_use": "Public / Semi-Public",
        "zoning": "Institutional (PS-1)",
        "jurisdiction": "Delhi NCT",
        "status": "Verified",
        "centroid_lat": 28.5320,
        "centroid_lng": 77.2380,
        "demo_scenario": "Profile H: Graceful Missing Module Demonstration (Partial Study)",
        "study_status": "PARTIALLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "planning", "tax"],
        "owner": {"name": "National Public Service Society", "relation": "Registered NGO", "share": "100%"},
        "enc": {"status": "Clear"},
        "tax": {"id": "MCD-TAX-2024-9922", "status": "Paid", "paid": "₹ 12,000", "date": "18 Aug 2024"},
        "ut": {"elec": "Connected", "water": "Connected", "sewer": "Connected", "gas": "Not Connected"},
        "coords": [
            {"lat": 28.5330, "lng": 77.2365},
            {"lat": 28.5340, "lng": 77.2392},
            {"lat": 28.5310, "lng": 77.2400},
            {"lat": 28.5300, "lng": 77.2372}
        ]
    },

    # ── Jaipur Heritage & Arid Corridor (3 plots) ─────────────────────────────
    {
        "parcel_id": "P-5201",
        "ulpin": "IN-RJ-JPR-0005201",
        "survey_no": "5201",
        "khata_no": "KH-JPR-55",
        "location": "Mansarovar Sector 3, Jaipur",
        "location_id": "jaipur",
        "state": "Rajasthan",
        "district": "Jaipur",
        "tehsil": "Jaipur",
        "rural_urban": "Urban",
        "original_area": 2.15,
        "original_unit": "Bigha",
        "standardized_area": 1460.00,
        "standardized_unit": "m²",
        "area_display": "1,460.00 m²",
        "original_area_display": "2.15 Bigha",
        "land_use": "Residential",
        "zoning": "Residential (R-2)",
        "jurisdiction": "Rajasthan",
        "status": "Verified",
        "centroid_lat": 26.9124,
        "centroid_lng": 75.7873,
        "demo_scenario": "Profile A: JDA Approved Khatedari Conversion Plotted Scheme",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "tax", "utilities", "ai"],
        "owner": {"name": "Mahaveer Prasad Sharma", "relation": "s/o B. L. Sharma", "share": "100%"},
        "bp": {"id": "JDA/BP/2023/511", "status": "Approved", "floors": "G + 2", "date": "23 Jul 2023"},
        "enc": {"status": "Clear"},
        "tax": {"id": "UDH-JPR-2024-771", "status": "Paid", "paid": "₹ 11,200", "date": "14 May 2024"},
        "ut": {"elec": "Connected (JVVNL)", "water": "Connected (PHED)", "sewer": "Connected", "gas": "Not Connected"},
        "coords": [
            {"lat": 26.9135, "lng": 75.7858},
            {"lat": 26.9145, "lng": 75.7885},
            {"lat": 26.9115, "lng": 75.7895},
            {"lat": 26.9105, "lng": 75.7868}
        ]
    },
    {
        "parcel_id": "P-5202",
        "ulpin": "IN-RJ-JPR-0005202",
        "survey_no": "5202",
        "khata_no": "KH-JPR-56",
        "location": "Sanganer Peri-Urban, Jaipur",
        "location_id": "jaipur",
        "state": "Rajasthan",
        "district": "Jaipur",
        "tehsil": "Sanganer",
        "rural_urban": "Rural",
        "original_area": 1.00,
        "original_unit": "Acre",
        "standardized_area": 4046.86,
        "standardized_unit": "m²",
        "area_display": "4,046.86 m²",
        "original_area_display": "1.00 Acre",
        "land_use": "Agricultural",
        "zoning": "Agricultural (Green Belt)",
        "jurisdiction": "Rajasthan",
        "status": "Verified",
        "centroid_lat": 26.9150,
        "centroid_lng": 75.7905,
        "demo_scenario": "Profile B: Co-ownership Agricultural Khatauni Jamabandi Record",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "tax"],
        "owner": {"name": "Ram Lal Meena & Brothers", "relation": "Co-Sharers", "share": "50% each"},
        "enc": {"status": "Clear"},
        "tax": {"id": "LAND-REV-2024-002", "status": "Paid", "paid": "₹ 480", "date": "02 Feb 2024"},
        "ut": {"elec": "Agricultural Pump Connection", "water": "Tube Well", "sewer": "Not Connected", "gas": "Not Connected"},
        "coords": [
            {"lat": 26.9162, "lng": 75.7890},
            {"lat": 26.9175, "lng": 75.7920},
            {"lat": 26.9140, "lng": 75.7930},
            {"lat": 26.9130, "lng": 75.7900}
        ]
    },
    {
        "parcel_id": "P-5203",
        "ulpin": "IN-RJ-JPR-0005203",
        "survey_no": "5203",
        "khata_no": "KH-JPR-57",
        "location": "Sitapura Industrial Area, Jaipur",
        "location_id": "jaipur",
        "state": "Rajasthan",
        "district": "Jaipur",
        "tehsil": "Sanganer",
        "rural_urban": "Urban",
        "original_area": 0.80,
        "original_unit": "Acre",
        "standardized_area": 3250.00,
        "standardized_unit": "m²",
        "area_display": "3,250.00 m²",
        "original_area_display": "0.80 Acre",
        "land_use": "Industrial",
        "zoning": "Industrial General (RIICO Zone)",
        "jurisdiction": "Rajasthan",
        "status": "Verified",
        "centroid_lat": 26.9095,
        "centroid_lng": 75.7840,
        "demo_scenario": "Profile E: RIICO Industrial Estate Plot with High-Tension Buffer",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "tax", "utilities", "restrictions"],
        "owner": {"name": "Rajasthan Precision Tools Pvt. Ltd.", "relation": "Corporate", "share": "100%"},
        "bp": {"id": "RIICO/BP/2021/104", "status": "Approved", "floors": "G + 1", "date": "17 Dec 2021"},
        "enc": {"status": "Clear"},
        "tax": {"id": "RIICO-TAX-2024-880", "status": "Paid", "paid": "₹ 44,000", "date": "10 Aug 2024"},
        "ut": {"elec": "HT Industrial Power", "water": "RIICO Water Network", "sewer": "Connected", "gas": "Available Nearby"},
        "coords": [
            {"lat": 26.9105, "lng": 75.7825},
            {"lat": 26.9118, "lng": 75.7852},
            {"lat": 26.9085, "lng": 75.7860},
            {"lat": 26.9075, "lng": 75.7832}
        ]
    },

    # ── Bengaluru High-Tech Urban (3 plots) ────────────────────────────────────
    {
        "parcel_id": "P-6301",
        "ulpin": "IN-KA-BLR-0006301",
        "survey_no": "6301",
        "khata_no": "KA-PID-991",
        "location": "Whitefield Tech Corridor, Bengaluru",
        "location_id": "bengaluru",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "tehsil": "Bengaluru East",
        "rural_urban": "Urban",
        "original_area": 0.86,
        "original_unit": "Acre",
        "standardized_area": 3500.00,
        "standardized_unit": "m²",
        "area_display": "3,500.00 m²",
        "original_area_display": "0.86 Acre",
        "land_use": "Commercial",
        "zoning": "High-Tech / IT Corridor (BDA Master Plan 2031)",
        "jurisdiction": "Karnataka",
        "status": "Verified",
        "centroid_lat": 12.9716,
        "centroid_lng": 77.5946,
        "demo_scenario": "Profile C: BDA Comprehensive Development Plan High FAR Plot",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "tax", "utilities", "ai"],
        "owner": {"name": "Silicon Heights Infrastructure LLP", "relation": "Entity", "share": "100%"},
        "bp": {"id": "BBMP/BP/2023/8901", "status": "Approved", "floors": "G + 8", "date": "14 Oct 2023"},
        "enc": {"status": "Clear"},
        "tax": {"id": "BBMP-SAS-2024-332", "status": "Paid", "paid": "₹ 1,45,000", "date": "18 May 2024"},
        "ut": {"elec": "Bescom Dual Feed HT", "water": "BWSSB Metered", "sewer": "Connected", "gas": "GAIL Gas Pipeline"},
        "coords": [
            {"lat": 12.9728, "lng": 77.5930},
            {"lat": 12.9738, "lng": 77.5960},
            {"lat": 12.9705, "lng": 77.5968},
            {"lat": 12.9695, "lng": 77.5938}
        ]
    },
    {
        "parcel_id": "P-6302",
        "ulpin": "IN-KA-BLR-0006302",
        "survey_no": "6302",
        "khata_no": "KA-PID-992",
        "location": "Indiranagar 100ft Road, Bengaluru",
        "location_id": "bengaluru",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "tehsil": "Bengaluru East",
        "rural_urban": "Urban",
        "original_area": 0.28,
        "original_unit": "Acre",
        "standardized_area": 1150.00,
        "standardized_unit": "m²",
        "area_display": "1,150.00 m²",
        "original_area_display": "0.28 Acre",
        "land_use": "Commercial",
        "zoning": "Commercial Mixed (C-2)",
        "jurisdiction": "Karnataka",
        "status": "Verified",
        "centroid_lat": 12.9745,
        "centroid_lng": 77.5980,
        "demo_scenario": "Profile D: IT Corridor Commercial Plot with Consortium Mortgage",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "liabilities", "tax"],
        "owner": {"name": "K. Venkatesh Murthy", "relation": "s/o Narayana Murthy", "share": "100%"},
        "bp": {"id": "BBMP/BP/2022/110", "status": "Approved", "floors": "G + 3", "date": "19 Feb 2022"},
        "enc": {"status": "Active", "inst": "Canara Bank", "amt": "₹ 1,20,00,000", "noc": True, "ref": "CNRB-BLR-2023-90"},
        "tax": {"id": "BBMP-SAS-2024-333", "status": "Paid", "paid": "₹ 48,000", "date": "11 Jun 2024"},
        "ut": {"elec": "Bescom Commercial", "water": "BWSSB", "sewer": "Connected", "gas": "GAIL Gas Pipeline"},
        "coords": [
            {"lat": 12.9755, "lng": 77.5965},
            {"lat": 12.9765, "lng": 77.5992},
            {"lat": 12.9735, "lng": 77.6000},
            {"lat": 12.9725, "lng": 77.5972}
        ]
    },
    {
        "parcel_id": "P-6303",
        "ulpin": "IN-KA-BLR-0006303",
        "survey_no": "6303",
        "khata_no": "KA-PID-993",
        "location": "Koramangala 4th Block, Bengaluru",
        "location_id": "bengaluru",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "tehsil": "Bengaluru South",
        "rural_urban": "Urban",
        "original_area": 0.22,
        "original_unit": "Acre",
        "standardized_area": 880.00,
        "standardized_unit": "m²",
        "area_display": "880.00 m²",
        "original_area_display": "0.22 Acre",
        "land_use": "Residential",
        "zoning": "Residential (R-4)",
        "jurisdiction": "Karnataka",
        "status": "Verified",
        "centroid_lat": 12.9685,
        "centroid_lng": 77.5910,
        "demo_scenario": "Profile E: BWSSB Smart Metered Water and Dual Bescom Power",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "tax", "utilities"],
        "owner": {"name": "Anoop Kumar & Priya Kumar", "relation": "Joint Spouses", "share": "50% each"},
        "enc": {"status": "Clear"},
        "tax": {"id": "BBMP-SAS-2024-334", "status": "Paid", "paid": "₹ 24,500", "date": "29 Jul 2024"},
        "ut": {"elec": "Bescom Solar Linked", "water": "BWSSB Smart Meter", "sewer": "Connected", "gas": "Piped Gas"},
        "coords": [
            {"lat": 12.9695, "lng": 77.5895},
            {"lat": 12.9705, "lng": 77.5922},
            {"lat": 12.9675, "lng": 77.5930},
            {"lat": 12.9665, "lng": 77.5902}
        ]
    },

    # ── Kochi Coastal & Backwaters (3 plots) ───────────────────────────────────
    {
        "parcel_id": "P-7401",
        "ulpin": "IN-KL-EKM-0007401",
        "survey_no": "7401",
        "khata_no": "TH-KOC-411",
        "location": "Marine Drive Coastal Fringe, Kochi",
        "location_id": "kochi",
        "state": "Kerala",
        "district": "Ernakulam",
        "tehsil": "Kanakayannur",
        "rural_urban": "Urban",
        "original_area": 0.47,
        "original_unit": "Acre",
        "standardized_area": 1920.00,
        "standardized_unit": "m²",
        "area_display": "1,920.00 m²",
        "original_area_display": "0.47 Acre",
        "land_use": "Mixed Coastal Commercial",
        "zoning": "Coastal Tourism & Mixed (CRZ-II)",
        "jurisdiction": "Kerala",
        "status": "Verified",
        "centroid_lat": 9.9312,
        "centroid_lng": 76.2673,
        "demo_scenario": "Profile C: CRZ-II Coastal Buffer Clearance Required",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "restrictions", "tax", "ai"],
        "owner": {"name": "Malabar Heritage Hospitality Ltd.", "relation": "Entity", "share": "100%"},
        "bp": {"id": "KOC/BP/2023/312", "status": "Approved", "floors": "G + 4", "date": "11 May 2023"},
        "enc": {"status": "Clear"},
        "tax": {"id": "CORP-KOC-2024-811", "status": "Paid", "paid": "₹ 52,000", "date": "20 Jun 2024"},
        "ut": {"elec": "KSEB 3-Phase", "water": "Kerala Water Authority", "sewer": "Connected", "gas": "Available Nearby"},
        "coords": [
            {"lat": 9.9322, "lng": 76.2658},
            {"lat": 9.9335, "lng": 76.2685},
            {"lat": 9.9302, "lng": 76.2695},
            {"lat": 9.9290, "lng": 76.2668}
        ]
    },
    {
        "parcel_id": "P-7402",
        "ulpin": "IN-KL-EKM-0007402",
        "survey_no": "7402",
        "khata_no": "TH-KOC-412",
        "location": "Fort Kochi Heritage Precinct, Kochi",
        "location_id": "kochi",
        "state": "Kerala",
        "district": "Ernakulam",
        "tehsil": "Kochi",
        "rural_urban": "Urban",
        "original_area": 0.21,
        "original_unit": "Acre",
        "standardized_area": 850.00,
        "standardized_unit": "m²",
        "area_display": "850.00 m²",
        "original_area_display": "0.21 Acre",
        "land_use": "Residential",
        "zoning": "Heritage Residential Zone (H-1)",
        "jurisdiction": "Kerala",
        "status": "Verified",
        "centroid_lat": 9.9340,
        "centroid_lng": 76.2705,
        "demo_scenario": "Profile A: Traditional Thandapper Land Tax Title Record",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "tax", "utilities"],
        "owner": {"name": "George Joseph Kurian", "relation": "s/o K. M. Kurian", "share": "100%"},
        "enc": {"status": "Clear"},
        "tax": {"id": "CORP-KOC-2024-812", "status": "Paid", "paid": "₹ 14,800", "date": "04 May 2024"},
        "ut": {"elec": "KSEB", "water": "KWA", "sewer": "Connected", "gas": "Not Connected"},
        "coords": [
            {"lat": 9.9350, "lng": 76.2690},
            {"lat": 9.9360, "lng": 76.2718},
            {"lat": 9.9330, "lng": 76.2725},
            {"lat": 9.9320, "lng": 76.2698}
        ]
    },
    {
        "parcel_id": "P-7403",
        "ulpin": "IN-KL-EKM-0007403",
        "survey_no": "7403",
        "khata_no": "TH-KOC-413",
        "location": "Willingdon Island Port Logistics Fringe",
        "location_id": "kochi",
        "state": "Kerala",
        "district": "Ernakulam",
        "tehsil": "Kochi",
        "rural_urban": "Urban",
        "original_area": 1.04,
        "original_unit": "Acre",
        "standardized_area": 4200.00,
        "standardized_unit": "m²",
        "area_display": "4,200.00 m²",
        "original_area_display": "1.04 Acre",
        "land_use": "Port Logistics & Warehousing",
        "zoning": "Maritime Logistics Zone (M-L)",
        "jurisdiction": "Kerala",
        "status": "Verified",
        "centroid_lat": 9.9280,
        "centroid_lng": 76.2640,
        "demo_scenario": "Profile E: Cochin Port Trust Statutory Ground Lease & Navigational Easement",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "planning", "tax", "utilities", "restrictions"],
        "owner": {"name": "Cochin Port Logistics Ltd.", "relation": "Govt Partner", "share": "100%"},
        "enc": {"status": "Clear"},
        "tax": {"id": "PORT-TAX-2024-001", "status": "Paid", "paid": "₹ 78,000", "date": "15 Jul 2024"},
        "ut": {"elec": "Industrial Feed", "water": "Bulk Supply", "sewer": "Connected", "gas": "Not Connected"},
        "coords": [
            {"lat": 9.9292, "lng": 76.2625},
            {"lat": 9.9305, "lng": 76.2652},
            {"lat": 9.9270, "lng": 76.2662},
            {"lat": 9.9258, "lng": 76.2632}
        ]
    },

    # ── Rural Varanasi / Indo-Gangetic (3 plots) ──────────────────────────────
    {
        "parcel_id": "P-8501",
        "ulpin": "IN-UP-VNS-0008501",
        "survey_no": "8501",
        "khata_no": "UP-KH-201",
        "location": "Shivpur Village Abadi, Varanasi",
        "location_id": "varanasi_rural",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "tehsil": "Sadar",
        "rural_urban": "Rural",
        "original_area": 0.15,
        "original_unit": "Acre",
        "standardized_area": 620.00,
        "standardized_unit": "m²",
        "area_display": "620.00 m²",
        "original_area_display": "0.15 Acre",
        "land_use": "Village Residential Abadi",
        "zoning": "Rural Abadi (SVAMITVA Scheme)",
        "jurisdiction": "Uttar Pradesh",
        "status": "Verified",
        "centroid_lat": 25.3176,
        "centroid_lng": 82.9739,
        "demo_scenario": "Profile B: SVAMITVA Drone Survey Inhabited Abadi Property Card",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "tax"],
        "owner": {"name": "Lalji Yadav", "relation": "s/o Ramdhari Yadav", "share": "100%"},
        "enc": {"status": "Clear"},
        "tax": {"id": "PANCH-VNS-2024-11", "status": "Paid", "paid": "₹ 250", "date": "12 Mar 2024"},
        "ut": {"elec": "Connected (Saubhagya Scheme)", "water": "Jal Jeevan Mission Tap", "sewer": "Village Soakpit", "gas": "Ujjwala LPG"},
        "coords": [
            {"lat": 25.3186, "lng": 82.9725},
            {"lat": 25.3195, "lng": 82.9750},
            {"lat": 25.3168, "lng": 82.9758},
            {"lat": 25.3158, "lng": 82.9732}
        ]
    },
    {
        "parcel_id": "P-8502",
        "ulpin": "IN-UP-VNS-0008502",
        "survey_no": "8502",
        "khata_no": "UP-KH-202",
        "location": "Cholapur Agricultural Plain, Varanasi",
        "location_id": "varanasi_rural",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "tehsil": "Pindra",
        "rural_urban": "Rural",
        "original_area": 1.28,
        "original_unit": "Acre",
        "standardized_area": 5200.00,
        "standardized_unit": "m²",
        "area_display": "5,200.00 m²",
        "original_area_display": "1.28 Acre",
        "land_use": "Agricultural",
        "zoning": "Multi-Crop Irrigated Agricultural",
        "jurisdiction": "Uttar Pradesh",
        "status": "Verified",
        "centroid_lat": 25.3210,
        "centroid_lng": 82.9775,
        "demo_scenario": "Profile B: UP Revenue Code Khatauni Multi-Heir RoR",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "planning", "tax"],
        "owner": {"name": "Shyam Sundar & Sons", "relation": "Joint Family", "share": "100%"},
        "enc": {"status": "Clear"},
        "tax": {"id": "UP-REV-2024-554", "status": "Paid", "paid": "₹ 620", "date": "29 Jan 2024"},
        "ut": {"elec": "Kisan Feeder Electricity", "water": "Canal Irrigation", "sewer": "Not Applicable", "gas": "Not Applicable"},
        "coords": [
            {"lat": 25.3225, "lng": 82.9758},
            {"lat": 25.3238, "lng": 82.9790},
            {"lat": 25.3198, "lng": 82.9802},
            {"lat": 25.3185, "lng": 82.9770}
        ]
    },
    {
        "parcel_id": "P-8503",
        "ulpin": "IN-UP-VNS-0008503",
        "survey_no": "8503",
        "khata_no": "UP-KH-203",
        "location": "Sarnath Heritage Buffer, Varanasi",
        "location_id": "varanasi_rural",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "tehsil": "Sadar",
        "rural_urban": "Peri-Urban",
        "original_area": 0.43,
        "original_unit": "Acre",
        "standardized_area": 1750.00,
        "standardized_unit": "m²",
        "area_display": "1,750.00 m²",
        "original_area_display": "0.43 Acre",
        "land_use": "Buffer Zone",
        "zoning": "Archaeological Heritage Buffer (ASI Prohibited 100m)",
        "jurisdiction": "Uttar Pradesh",
        "status": "Flagged",
        "centroid_lat": 25.3140,
        "centroid_lng": 82.9700,
        "demo_scenario": "Profile F: ASI Archaeological Protection Buffer Conflict",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "planning", "restrictions", "conflict"],
        "owner": {"name": "Banaras Heritage Preservation Society", "relation": "Trust", "share": "100%"},
        "enc": {"status": "Clear"},
        "tax": {"id": "VDA-TAX-2024-099", "status": "Paid", "paid": "₹ 3,400", "date": "14 May 2024"},
        "ut": {"elec": "Connected", "water": "Connected", "sewer": "Connected", "gas": "Not Connected"},
        "coords": [
            {"lat": 25.3152, "lng": 82.9685},
            {"lat": 25.3162, "lng": 82.9712},
            {"lat": 25.3130, "lng": 82.9720},
            {"lat": 25.3120, "lng": 82.9692}
        ]
    },

    # ── Pune Industrial Corridor (3 plots) ────────────────────────────────────
    {
        "parcel_id": "P-9601",
        "ulpin": "IN-MH-PUN-0009601",
        "survey_no": "9601",
        "khata_no": "MH-712-401",
        "location": "Hinjewadi Phase 1, Pune",
        "location_id": "pune_industrial",
        "state": "Maharashtra",
        "district": "Pune",
        "tehsil": "Mulshi",
        "rural_urban": "Urban",
        "original_area": 1.19,
        "original_unit": "Acre",
        "standardized_area": 4800.00,
        "standardized_unit": "m²",
        "area_display": "4,800.00 m²",
        "original_area_display": "1.19 Acre",
        "land_use": "Industrial",
        "zoning": "Heavy Industrial & Logistics (MIDC Zone)",
        "jurisdiction": "Maharashtra",
        "status": "Verified",
        "centroid_lat": 18.5204,
        "centroid_lng": 73.8567,
        "demo_scenario": "Profile E: MIDC Sub-Lease with Industrial Effluent Pipeline Easement",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "tax", "utilities", "restrictions", "ai"],
        "owner": {"name": "Maharashtra Heavy Polymers Pvt. Ltd.", "relation": "Industrialist", "share": "100%"},
        "bp": {"id": "MIDC/BP/2022/904", "status": "Approved", "floors": "G + 1", "date": "08 Sep 2022"},
        "enc": {"status": "Clear"},
        "tax": {"id": "MIDC-TAX-2024-712", "status": "Paid", "paid": "₹ 82,000", "date": "19 May 2024"},
        "ut": {"elec": "MSEDCL HT Supply", "water": "MIDC Industrial Water", "sewer": "CETP Connection", "gas": "MNGL Natural Gas"},
        "coords": [
            {"lat": 18.5218, "lng": 73.8548},
            {"lat": 18.5230, "lng": 73.8580},
            {"lat": 18.5195, "lng": 73.8590},
            {"lat": 18.5182, "lng": 73.8558}
        ]
    },
    {
        "parcel_id": "P-9602",
        "ulpin": "IN-MH-PUN-0009602",
        "survey_no": "9602",
        "khata_no": "MH-712-402",
        "location": "Wakad Plotted Commercial, Pune",
        "location_id": "pune_industrial",
        "state": "Maharashtra",
        "district": "Pune",
        "tehsil": "Haveli",
        "rural_urban": "Urban",
        "original_area": 0.40,
        "original_unit": "Acre",
        "standardized_area": 1600.00,
        "standardized_unit": "m²",
        "area_display": "1,600.00 m²",
        "original_area_display": "0.40 Acre",
        "land_use": "Commercial",
        "zoning": "Commercial (C-3)",
        "jurisdiction": "Maharashtra",
        "status": "Verified",
        "centroid_lat": 18.5235,
        "centroid_lng": 73.8600,
        "demo_scenario": "Profile D: Commercial Hypothecation with Active Axis Bank Mortgage",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "liabilities", "tax"],
        "owner": {"name": "Ganesh Kulkarni", "relation": "s/o V. R. Kulkarni", "share": "100%"},
        "bp": {"id": "PCMC/BP/2023/118", "status": "Approved", "floors": "G + 4", "date": "14 Mar 2023"},
        "enc": {"status": "Active", "inst": "Axis Bank Ltd.", "amt": "₹ 85,00,000", "noc": True, "ref": "AXIS-PUN-2023-11"},
        "tax": {"id": "PCMC-TAX-2024-551", "status": "Paid", "paid": "₹ 38,500", "date": "17 Jul 2024"},
        "ut": {"elec": "MSEDCL", "water": "PCMC Water", "sewer": "Connected", "gas": "MNGL Natural Gas"},
        "coords": [
            {"lat": 18.5245, "lng": 73.8585},
            {"lat": 18.5255, "lng": 73.8612},
            {"lat": 18.5225, "lng": 73.8620},
            {"lat": 18.5215, "lng": 73.8592}
        ]
    },
    {
        "parcel_id": "P-9603",
        "ulpin": "IN-MH-PUN-0009603",
        "survey_no": "9603",
        "khata_no": "MH-712-403",
        "location": "Baner High-Density Plotted, Pune",
        "location_id": "pune_industrial",
        "state": "Maharashtra",
        "district": "Pune",
        "tehsil": "Haveli",
        "rural_urban": "Urban",
        "original_area": 0.33,
        "original_unit": "Acre",
        "standardized_area": 1350.00,
        "standardized_unit": "m²",
        "area_display": "1,350.00 m²",
        "original_area_display": "0.33 Acre",
        "land_use": "Residential",
        "zoning": "Residential (R-3)",
        "jurisdiction": "Maharashtra",
        "status": "Verified",
        "centroid_lat": 18.5170,
        "centroid_lng": 73.8530,
        "demo_scenario": "Profile A: Maharashtra 7/12 Extract Computerized Land Record",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": True,
        "satellite_status": "AVAILABLE",
        "available_modules": ["ownership", "ror", "registration", "planning", "building", "tax", "utilities"],
        "owner": {"name": "Pooja Deshmukh", "relation": "w/o Rahul Deshmukh", "share": "100%"},
        "bp": {"id": "PMC/BP/2023/880", "status": "Approved", "floors": "G + 3", "date": "06 Nov 2023"},
        "enc": {"status": "Clear"},
        "tax": {"id": "PMC-TAX-2024-419", "status": "Paid", "paid": "₹ 27,200", "date": "12 Aug 2024"},
        "ut": {"elec": "Connected", "water": "Connected", "sewer": "Connected", "gas": "MNGL Piped Gas"},
        "coords": [
            {"lat": 18.5180, "lng": 73.8515},
            {"lat": 18.5190, "lng": 73.8542},
            {"lat": 18.5160, "lng": 73.8550},
            {"lat": 18.5150, "lng": 73.8522}
        ]
    },

    # ── Shimla Hills (NON-SENTINEL Study Area) (3 plots) ──────────────────────
    {
        "parcel_id": "P-9701",
        "ulpin": "IN-HP-SML-0009701",
        "survey_no": "9701",
        "khata_no": "HP-KH-801",
        "location": "The Mall Heritage Ridge, Shimla",
        "location_id": "shimla_hills",
        "state": "Himachal Pradesh",
        "district": "Shimla",
        "tehsil": "Shimla Urban",
        "rural_urban": "Urban",
        "original_area": 0.18,
        "original_unit": "Acre",
        "standardized_area": 740.00,
        "standardized_unit": "m²",
        "area_display": "740.00 m²",
        "original_area_display": "0.18 Acre",
        "land_use": "Commercial Heritage",
        "zoning": "Heritage Zone (Core Mall Road)",
        "jurisdiction": "Himachal Pradesh",
        "status": "Protected",
        "centroid_lat": 31.1048,
        "centroid_lng": 77.1734,
        "demo_scenario": "Profile C: Section 118 HP Tenancy Act Non-Agriculturist Transfer Restriction",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": False,
        "satellite_status": "NOT_AVAILABLE_FOR_THIS_DEMO_LOCATION",
        "available_modules": ["ownership", "ror", "registration", "planning", "restrictions", "tax"],
        "owner": {"name": "Himachal Heritage Properties Corp.", "relation": "Govt Undertaking", "share": "100%"},
        "enc": {"status": "Clear"},
        "tax": {"id": "SMC-TAX-2024-091", "status": "Paid", "paid": "₹ 29,000", "date": "10 Jul 2024"},
        "ut": {"elec": "HPSEBL", "water": "SMC Water", "sewer": "Connected", "gas": "LPG Bottled"},
        "coords": [
            {"lat": 31.1058, "lng": 77.1720},
            {"lat": 31.1068, "lng": 77.1745},
            {"lat": 31.1038, "lng": 77.1752},
            {"lat": 31.1028, "lng": 77.1728}
        ]
    },
    {
        "parcel_id": "P-9702",
        "ulpin": "IN-HP-SML-0009702",
        "survey_no": "9702",
        "khata_no": "HP-KH-802",
        "location": "Sanjauli Slope Settlement, Shimla",
        "location_id": "shimla_hills",
        "state": "Himachal Pradesh",
        "district": "Shimla",
        "tehsil": "Shimla Rural",
        "rural_urban": "Urban",
        "original_area": 0.23,
        "original_unit": "Acre",
        "standardized_area": 920.00,
        "standardized_unit": "m²",
        "area_display": "920.00 m²",
        "original_area_display": "0.23 Acre",
        "land_use": "Residential",
        "zoning": "Steep Slope Residential (NGT Controlled)",
        "jurisdiction": "Himachal Pradesh",
        "status": "Verified",
        "centroid_lat": 31.1080,
        "centroid_lng": 77.1770,
        "demo_scenario": "Profile H: Mountain Slope Construction Buffer (Graceful Missing Satellite)",
        "study_status": "PARTIALLY_STUDIED",
        "satellite_coverage": False,
        "satellite_status": "NOT_AVAILABLE_FOR_THIS_DEMO_LOCATION",
        "available_modules": ["ownership", "ror", "planning", "restrictions", "tax"],
        "owner": {"name": "Prem Chand Thakur", "relation": "s/o N. R. Thakur", "share": "100%"},
        "enc": {"status": "Clear"},
        "tax": {"id": "SMC-TAX-2024-092", "status": "Paid", "paid": "₹ 11,400", "date": "18 Aug 2024"},
        "ut": {"elec": "HPSEBL", "water": "SMC Water", "sewer": "Connected", "gas": "LPG Bottled"},
        "coords": [
            {"lat": 31.1090, "lng": 77.1755},
            {"lat": 31.1100, "lng": 77.1782},
            {"lat": 31.1070, "lng": 77.1790},
            {"lat": 31.1060, "lng": 77.1762}
        ]
    },
    {
        "parcel_id": "P-9703",
        "ulpin": "IN-HP-SML-0009703",
        "survey_no": "9703",
        "khata_no": "HP-KH-803",
        "location": "Chhota Shimla Institutional Enclave",
        "location_id": "shimla_hills",
        "state": "Himachal Pradesh",
        "district": "Shimla",
        "tehsil": "Shimla Urban",
        "rural_urban": "Urban",
        "original_area": 0.69,
        "original_unit": "Acre",
        "standardized_area": 2800.00,
        "standardized_unit": "m²",
        "area_display": "2,800.00 m²",
        "original_area_display": "0.69 Acre",
        "land_use": "Administrative Institutional",
        "zoning": "Government Institutional Zone",
        "jurisdiction": "Himachal Pradesh",
        "status": "Verified",
        "centroid_lat": 31.1015,
        "centroid_lng": 77.1700,
        "demo_scenario": "Profile E: Municipal Hill Drainage & Slope Stability Clearance",
        "study_status": "FULLY_STUDIED",
        "satellite_coverage": False,
        "satellite_status": "NOT_AVAILABLE_FOR_THIS_DEMO_LOCATION",
        "available_modules": ["ownership", "ror", "planning", "building", "tax", "utilities"],
        "owner": {"name": "HP State Administrative Directorate", "relation": "State Govt", "share": "100%"},
        "bp": {"id": "TCP/HP/2021/045", "status": "Approved", "floors": "G + 3", "date": "12 Nov 2021"},
        "enc": {"status": "Clear"},
        "tax": {"id": "SMC-TAX-2024-093", "status": "Exempt", "paid": "₹ 0", "date": "01 Apr 2024"},
        "ut": {"elec": "HPSEBL", "water": "SMC", "sewer": "Connected", "gas": "Central Heating"},
        "coords": [
            {"lat": 31.1025, "lng": 77.1685},
            {"lat": 31.1035, "lng": 77.1712},
            {"lat": 31.1005, "lng": 77.1720},
            {"lat": 31.0995, "lng": 77.1692}
        ]
    }
]
